apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRUjgxeXNjY3F3ejFmUzYycVpZZTJHekFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNRGN4TkRFd01qRTBObG9YRFRNMU1EY3hNakV3TWpFMApObG93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCTTBJVDFKNDQzY2VmZWNjdUpkQWxKY0xmK1ZzNVdvRGNFMFBGR2puZmFFL21DVmFLTEJLdW43MnBRUGoKNkNXRkMrRUxxN3lzczdQQmc2UTE2Z0RDZnp1allUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU0THNGSm16ZVFwNDlZUENvdWV3TFdTZGV2a2N3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnWnVzZ1hLZVoKRE1WODl1d0RKWllRb1JVN0RxRmtWQWhDR0tnbGlKdDVIRGtDSUhHVkhFMU8rTnNHM2haalk1MkhIak5NdXlETApkaWtFaDRrd2V0WDFOTHlvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://10.96.0.1:443
  name: public-poesis-cluster
contexts:
- context:
    cluster: public-poesis-cluster
    namespace: default
    user: admin@public-poesis-cluster
  name: admin@public-poesis-cluster
current-context: admin@public-poesis-cluster
kind: Config
preferences: {}
users:
- name: admin@public-poesis-cluster
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJoakNDQVN1Z0F3SUJBZ0lSQU96NzVRWmVYSWNFQzV3MTEvSS9WRVV3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVDaE1LYTNWaVpYSnVaWFJsY3pBZUZ3MHlOVEEzTVRReE1ESTNOVFZhRncweU5qQTNNVFF4TURJNApNRFZhTUNreEZ6QVZCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE0d0RBWURWUVFERXdWaFpHMXBiakJaCk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkpSVi9zRVExaWRQWTh4SFd5Q1NscVZVR25iUk9kcTIKUGJtZmtFREtiQUx2cUN2Z3ErQ0ZhdHRiajNGeTJjRXFWSXpsWmNvMnc5NWxKa0kwV21ud004Q2pTREJHTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VFRERBS0JnZ3JCZ0VGQlFjREFqQWZCZ05WSFNNRUdEQVdnQlRnCnV3VW1iTjVDbmoxZzhLaTU3QXRaSjE2K1J6QUtCZ2dxaGtqT1BRUURBZ05KQURCR0FpRUFoZ05mdUUyOVJzOUMKVkt1L3ZuZmYvSWVmRXFGcUp3ejNTR1IycWtrUzZjY0NJUUNzOXFjMGd2TzZqelFkTlF6L0hMVDg1Ty9SQnJqNwovSURzSWtqMmVPV29sUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1WTTl5bVV1Z3o3R1BGZ1Z2dkdDYU9vQW1ieWluWUhQMmlUTmdYRUlhUjBvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbEZYK3dSRFdKMDlqekVkYklKS1dwVlFhZHRFNTJyWTl1WitRUU1wc0F1K29LK0NyNElWcQoyMXVQY1hMWndTcFVqT1ZseWpiRDNtVW1RalJhYWZBendBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=