"""
Migration utilities to transition from monolithic to clean architecture
"""

import os
import shutil
from pathlib import Path
from typing import Dict, Any
import logging

logger = logging.getLogger(__name__)


def backup_original_app(backup_dir: str = "backup_original") -> None:
    """Backup the original monolithic app.py"""
    current_dir = Path(__file__).parent
    original_app = current_dir / "app.py"
    backup_path = current_dir / backup_dir
    
    if original_app.exists():
        backup_path.mkdir(exist_ok=True)
        shutil.copy2(original_app, backup_path / "app.py")
        logger.info(f"Backed up original app.py to {backup_path}")


def create_environment_config() -> Dict[str, Any]:
    """Create environment configuration for the new architecture"""
    config = {
        # Framework selection
        'WEB_FRAMEWORK': 'flask',  # or 'fastapi'
        'HOST': '0.0.0.0',
        'PORT': '8080',
        'DEBUG': 'false',
        
        # TES Configuration
        'TES_GATEWAY_URL': 'https://tes.prodrun.cloud',
        'TES_CLIENT_CERT': 'client-cert.pem',
        'TES_CLIENT_KEY': 'client-key.pem',
        'TES_LOCATIONS_FILE': 'tes_instance_locations.json',
        
        # Storage Configuration
        'UPLOAD_DIR': 'uploads',
        'WORK_DIR': 'work',
        'MAX_UPLOAD_SIZE': '16777216',  # 16MB
        
        # CORS Configuration
        'CORS_ENABLED': 'true',
        'CORS_ORIGINS': 'http://localhost:3000,http://127.0.0.1:3000',
        
        # Logging
        'LOG_LEVEL': 'INFO',
        'LOG_FILE': 'dashboard.log'
    }
    return config


def create_env_file(config: Dict[str, Any], filename: str = ".env") -> None:
    """Create .env file with configuration"""
    current_dir = Path(__file__).parent
    env_path = current_dir / filename
    
    with open(env_path, 'w') as f:
        f.write("# TES Dashboard Environment Configuration\n")
        f.write("# Generated by migration script\n\n")
        
        for key, value in config.items():
            f.write(f"{key}={value}\n")
    
    logger.info(f"Created environment configuration: {env_path}")


def create_requirements_new() -> None:
    """Create new requirements.txt with framework-agnostic dependencies"""
    requirements = """# Framework-agnostic TES Dashboard Requirements
# Core dependencies
requests>=2.31.0
pydantic>=2.0.0
python-dotenv>=1.0.0

# Framework options (choose one or both)
flask>=2.3.0
flask-cors>=4.0.0

# FastAPI alternative (optional)
fastapi>=0.104.0
uvicorn>=0.24.0

# Development dependencies
pytest>=7.4.0
pytest-asyncio>=0.21.0
black>=23.0.0
mypy>=1.5.0

# Original dependencies (if still needed)
urllib3>=2.0.0
certifi>=2023.0.0
"""
    
    current_dir = Path(__file__).parent
    req_path = current_dir / "requirements_new.txt"
    
    with open(req_path, 'w') as f:
        f.write(requirements)
    
    logger.info(f"Created new requirements: {req_path}")


def create_migration_guide() -> None:
    """Create migration guide documentation"""
    guide = """# Migration Guide: From Monolithic to Clean Architecture

## Overview
This migration transforms the monolithic Flask app into a framework-agnostic clean architecture.

## Architecture Changes

### Before (Monolithic)
```
app.py (4,788 lines)
├── Flask routes
├── Business logic
├── Data access
└── Framework coupling
```

### After (Clean Architecture)
```
backend/
├── core/
│   ├── models/          # Domain models
│   ├── services/        # Business logic
│   ├── repositories/    # Data access
│   └── config.py        # Configuration
├── adapters/
│   └── web/
│       ├── flask_adapter.py    # Flask-specific
│       └── fastapi_adapter.py  # FastAPI alternative
├── app_factory.py       # Application factory
└── main.py             # Entry point
```

## Migration Steps

### 1. Backup Original Code
```bash
python -c "from migration_utils import backup_original_app; backup_original_app()"
```

### 2. Install New Dependencies
```bash
pip install -r requirements_new.txt
```

### 3. Set Up Environment
```bash
# Copy generated .env file to your environment
cp .env.example .env
# Edit .env with your specific configuration
```

### 4. Start New Application
```bash
# Using Flask (default)
python main.py

# Using FastAPI (set environment variable)
WEB_FRAMEWORK=fastapi python main.py
```

## Benefits

### Framework Independence
- Business logic separated from web framework
- Easy migration between Flask/FastAPI/Django
- Testable business services

### Clean Architecture
- Domain models in `core/models`
- Business logic in `core/services` 
- Data access in `core/repositories`
- Web adapters in `adapters/web`

### Improved Maintainability
- Single responsibility principle
- Dependency injection
- Separation of concerns
- Easier testing

## Compatibility

### API Compatibility
All existing API endpoints maintained:
- `/api/dashboard_data`
- `/api/batch_runs`
- `/api/batch_log/{run_id}`
- `/api/batch_nextflow`
- `/api/batch_snakemake`
- `/api/batch_cwl`

### Frontend Compatibility
No frontend changes required - all API contracts preserved.

## Testing

### Unit Tests
```bash
# Test business logic (framework-independent)
pytest tests/core/

# Test web adapters
pytest tests/adapters/
```

### Integration Tests
```bash
# Test complete application
pytest tests/integration/
```

## Rollback Plan

1. Stop new application
2. Restore original `app.py` from backup
3. Install original requirements
4. Start original application

## Framework Migration Examples

### Flask to FastAPI
```bash
# Change environment variable
export WEB_FRAMEWORK=fastapi
python main.py
```

### Add New Framework
1. Create adapter in `adapters/web/new_framework_adapter.py`
2. Update `app_factory.py`
3. Test with existing business logic

## Configuration Management

### Environment Variables
- `WEB_FRAMEWORK`: Choose framework (flask/fastapi)
- `TES_GATEWAY_URL`: TES gateway endpoint
- `UPLOAD_DIR`: File upload directory
- `CORS_ORIGINS`: Allowed CORS origins

### Framework-Specific Settings
- Flask: Uses Flask configuration
- FastAPI: Uses Pydantic settings
- Both: Share core business configuration

## Monitoring and Logging

### Structured Logging
```python
import logging
logger = logging.getLogger(__name__)
logger.info("Business operation completed", extra={"workflow_id": "123"})
```

### Health Checks
- `/api/test_connection` - Basic connectivity
- Business service health via dependency injection

## Support

### Documentation
- Core models: `backend/core/models/__init__.py`
- Business services: `backend/core/services/__init__.py`
- Repository pattern: `backend/core/repositories/__init__.py`

### Debugging
1. Enable debug logging: `export LOG_LEVEL=DEBUG`
2. Check business logic: Services are framework-independent
3. Check web layer: Framework-specific adapters

## Future Enhancements

### Easy Framework Addition
1. Create new adapter: `adapters/web/django_adapter.py`
2. Update factory: Add Django option
3. Business logic remains unchanged

### Microservices Migration
- Extract services: `TESClientService` → separate microservice
- Add HTTP repository: Replace file-based storage
- Maintain API contracts: Frontend unchanged

"""

    current_dir = Path(__file__).parent
    guide_path = current_dir / "MIGRATION_GUIDE.md"
    
    with open(guide_path, 'w') as f:
        f.write(guide)
    
    logger.info(f"Created migration guide: {guide_path}")


def run_migration():
    """Run complete migration process"""
    logger.info("Starting migration to clean architecture...")
    
    # 1. Backup original app
    backup_original_app()
    
    # 2. Create environment configuration
    config = create_environment_config()
    create_env_file(config)
    
    # 3. Create new requirements
    create_requirements_new()
    
    # 4. Create migration guide
    create_migration_guide()
    
    logger.info("Migration preparation complete!")
    logger.info("Next steps:")
    logger.info("1. Review and edit .env file")
    logger.info("2. Install new dependencies: pip install -r requirements_new.txt")
    logger.info("3. Start new application: python main.py")
    logger.info("4. Read MIGRATION_GUIDE.md for details")


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    run_migration()
