name: Open Shift Deployment

on:
  push:
    branches: ['master']

jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn lint

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: E2E run
        uses: cypress-io/github-action@v4
        with:
          build: yarn build
          start: yarn dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile

  docker-image:
    runs-on: ubuntu-latest
    needs: [linters, tests]

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKERHUB_LOGIN }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
      - name: Build Docker Image
        run: docker build -f Dockerfile -t anurag1201/krini:latest .
      - name: Docker Push
        run: docker push anurag1201/krini:latest

  open-shift:
    runs-on: ubuntu-latest
    needs: [docker-image, linters, tests]
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install oc
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: 4
      - name: Log in to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          insecure_skip_tls_verify: true
          # namespace: krini
          # openshift_username: ${{ secrets.OPENSHIFT_USER }}
          # openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
      - name: Switch to project Krini
        run: oc project krini
      - name: Trigger Build
        run: oc rollout latest "krini"
      - name: OpenShift Logout
        run: oc logout
